#! /bin/bash

set -e

cd Agda

if [ ! -e "$HOME/lib/agda-stdlib-0.12" ]; then
  echo "  Extracting Agda stdlib"
  tar -xf agda-stdlib-0.12.tar.gz -C $HOME/lib
fi

HERE=$HOME/config/Agda
THERE=$HOME/repos/clones
#
# Version 2.4.2.5
#COMMIT="25535a39a924bb893ff4887a61dc654e5e3a1522"

#
# Version 2.5.0
COMMIT="98762de0879701eea297489c829a3ec7b1de12d1"

function agdaClone() {
  echo "  Cloning Agda"
  cd $THERE
  git clone git@github.com:agda/agda.git
  cd $HERE
}

function agdaFwd() {
  cd $THERE/agda
  curr=$(git log | head -n 1 | cut -d ' ' -f 2)
  if [[ "$curr" == "$COMMIT" ]]; then
    echo "    Repo is already at $COMMIT"
  else
    echo "    Repo is at $curr"
    echo "    We want $COMMIT"
    read -p "      shoul we checkout (y/n) ? " ans
    case $ans in
      [Yy])
        git checkout $COMMIT
      ;;
    esac
  fi
  cd $HERE
}

function agdaInstall() {
  echo "  Going to compile agda, this might take some time"
  read -p "  continue (y/n) ?" ans
  case $ans in
    [Yy])
      cd $THERE/agda
      cabal sandbox init
      cabal install --only-dependencies
      cabal configure
      cabal build
      cp dist/build/agda/agda $HOME/bin/agda
      cp dist/build/agda-mode/agda-mode $HOME/bin/agda-mode
      mkdir -p ./.cabal-sandbox/share/x86_64-linux-ghc-7.10.3
      cp -R src/data ./.cabal-sandbox/share/x86_64-linux-ghc-7.10.3/Agda-2.6.0
      cd $HERE
      
    ;;
  esac
}


if [ ! -e "$THERE/agda" ]; then
  agdaClone
  agdaFwd
  agdaInstall
else
  agdaFwd
  agdaInstall
fi

cd ..
