#! /bin/bash

function cleanOne() {
  if $(pkg-is-installed $1); then
    read -p "Purgning $1; continue? (y/n) " ans
    case $ans in
      [Yy])
        sudo apt-get purge -y $1
      ;;
    esac
  fi
}

for i in $(cfg-linesof UnwantedPackages); do
  cleanOne $i
done
