#! /bin/bash

if [[ ! "$(owncloud --version)" =~ "2.1.1" ]]; then
  >&2 echo "!!! Expected: owncloud-client-2.1.1"
  read -p "    continue anyway (y/n) ? " ans
  case $ans in
    [Nn]) exit 0;;
  esac
fi 

HERE=$HOME/config/ownCloud
OWNCLOUD=$HOME/.local/share/data/ownCloud
##
## ownCloud syncExlucde list
##
echo "-- ownCloud client configuration:"
if [ ! -s $HOME/var/state/cfg.ownCloud ]; then
  test $HERE/sync-exclude.lst -nt $OWNCLOUD/sync-exclude.lst \
    && cp $HERE/sync-exclude.lst $OWNCLOUD/sync-exclude.lst \
    && echo "    Copied sync-exclude.lst"

  test $HERE/owncloud.cfg -nt $OWNCLOUD/owncloud.cfg \
    && cp $HERE/owncloud.cfg $OWNCLOUD/owncloud.cfg \
    && echo "    Copied owncloud.cfg"

  echo 'echo "1" > $HOME/var/state/cfg.ownCloud' | sudo bash
fi
