#! /bin/bash

if (( $# != 1 )); then
  echo "usage: pdf-to-monochrome file.pdf"
  echo ""
  exit 1
fi

if [[ ! -e $1 ]]; then
  echo "File $1 not found."
  exit 1;
fi

SRC=$1
DST="${1%pdf}mono.pdf"
convert -colorspace GRAY -density 400 -quality 100 $SRC $DST
